
import styles from '../../../styles/Home.module.css'

const Header = () => {
    return (
        <>
            <title>Notebooks</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.png" />
        </>
    )
}
export default Header;